GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJqYXNzb24iLCJlbWFpbCI6ImVtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTcyODIwNjM2NiwiZXhwIjoxNzI4MjA2OTY2fQ.dp4V9F9nMUv-n9EGl0Nb0t0YaeCyRvYhm6LCNSDsG-M
###
POST http://localhost:5001/users
Content-Type: application/json

{
    "name" : "jasson",
    "email" : "email@gmail.com",
    "password" : "123456",
    "confPassword" : "123456"
}
###
POST http://localhost:5001/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "123456"
}